/* ____ _  _ ____ _  _ _    ___  ____ _   _ __  __ _____ ____
  / ___| || |  _ \\ \\/ / |  / _ \\/ ___| | | |  \\/  | ____|  _ \\
 | |  _| || | |_) \\  /| | | | | |  _| | | | |\\/| |  _| | |_) |
 | |_| |  _|  __//  \\| |_| |_| | |_| |_| | |  | | |___|  _ <
  \\____|_| |_| /_/\\_\\____\\____/ \\____\\___/|_|  |_|_____|_| \\_\\

  Firefox Performant Privacy Edition
  Based on arkenfox + Betterfox recommendations
  Version: 150.1
  License: MIT

  Credits:
    - arkenfox: https://github.com/arkenfox/user.js
    - Betterfox: https://github.com/yokoffing/Betterfox
    - Mozilla Vertical Tabs (FF136+): native sidebar redesign

  INSTALL:
    1. Save this file to your Firefox profile as user.js:
         ~/.mozilla/firefox/<profile>/user.js
    2. Start Firefox (or restart)
    3. In about:config, accept the risk warning
    4. If ETP Strict shows a confirmation dialog, click "Enable"
    5. Optional tweaks: create user-overrides.js in same folder

  SYSTEM:
    - Target RAM: 16 GB
    - Target OS: Linux (Arch)
    - Target Firefox: 150+

/*********************************************************************/

// REQUIRED READING
// Read https://github.com/arkenfox/user.js/wiki before using
// Betterfox: https://github.com/yokoffing/Betterfox/wiki

/********************************************************************\
*  DO NOT EDIT THIS FILE FOR OVERRIDES
*  - Create user-overrides.js instead with your customizations
*  - This preserves changes across updates to this config
*
*  Common overrides (in user-overrides.js):
*    // Re-enable Safe Browsing (if you're OK with Google):
*    // user_pref("browser.safebrowsing.malware.enabled", true);
*    // user_pref("browser.safebrowsing.phishing.enabled", true);
*
*    // Change DoH provider:
*    // user_pref("network.trr.uri", "https://dns.google/dns-query");
*    // user_pref("network.trr.mode", 2);
*
*    // Disable certificate warning bypass:
*    // user_pref("browser.xul.error_pages.expert_bad_site", false);
*
*    // Limit RAM usage further (if OOM issues):
*    // user_pref("browser.cache.memory.capacity", 65536);
*    // user_pref("browser.sessionstore.max_tabs_undo", 0);
\
********************************************************************/

/* parroty */
user_pref("_user.js.parrot", "START: he's not dead, he's restin'!");

/*** [SECTION 0100]: STARTUP ***/
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.startup.page", 0);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredCheckboxes", false);
user_pref("browser.newtabpage.activity-stream.default.sites", "");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.shell.checkDefaultBrowser", false);

/*** [SECTION 0200]: GEOLOCATION ***/
user_pref("geo.provider.ms-windows-location", false);
user_pref("geo.provider.use_corelocation", false);
user_pref("geo.provider.use_geoclue", false);

/*** [SECTION 0300]: QUIETER FOX ***/
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
user_pref("browser.discovery.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
user_pref("captivedetect.canonicalURL", "");
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);

/*** [SECTION 0400]: SAFE BROWSING ***/
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");

/*** [SECTION 0500]: NATIVE VERTICAL TABS & SIDEBAR (FF136+) ***/
user_pref("sidebar.revamp", true);
user_pref("sidebar.revamp.defaultLauncherVisible", false);
user_pref("sidebar.position_start", false);
user_pref("sidebar.visibility", "always-show");
user_pref("sidebar.main.tools", "history,bookmarks");
user_pref("browser.sidebar.useCurrentTab", true);
user_pref("browser.sidebar.moveOnResize", false);
user_pref("browser.sidebar.width", 280);
user_pref("browser.sidebar.panels.animations", false);
user_pref("browser.tabs.allowAnimationPreference", false);
user_pref("browser.tabs.animate", false);
user_pref("browser.tabs.tabMinWidth", 76);
user_pref("browser.tabs.tabMaxWidth", 160);
user_pref("browser.tabs.tabClipWidth", 110);
user_pref("browser.ctrlTab.previews", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.bookmarks.showDesktopBookmarks", false);

/*** [SECTION 0600]: BLOCK IMPLICIT OUTBOUND ***/
user_pref("network.prefetch-next", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("browser.places.speculativeConnect.enabled", false);

/*** [SECTION 0700]: DNS / DoH / PROXY ***/
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.file.disable_unc_paths", true);
user_pref("network.gio.supported-protocols", "");
user_pref("network.trr.mode", 3);
user_pref("network.trr.uri", "https://dns.nextdns.io");
user_pref("network.dnsCacheEntries", 10000);
user_pref("network.dnsCacheExpiration", 3600);

/*** [SECTION 0800]: LOCATION BAR / SEARCH ***/
user_pref("browser.urlbar.speculativeConnect.enabled", false);
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.trending.featureGate", false);
user_pref("browser.urlbar.addons.featureGate", false);
user_pref("browser.urlbar.amp.featureGate", false);
user_pref("browser.urlbar.importantDates.featureGate", false);
user_pref("browser.urlbar.market.featureGate", false);
user_pref("browser.urlbar.mdn.featureGate", false);
user_pref("browser.urlbar.weather.featureGate", false);
user_pref("browser.urlbar.wikipedia.featureGate", false);
user_pref("browser.urlbar.yelp.featureGate", false);
user_pref("browser.urlbar.yelpRealtime.featureGate", false);
user_pref("browser.urlbar.clipboard.featureGate", false);
user_pref("browser.urlbar.trimHttps", true);
user_pref("browser.urlbar.untrimOnUserInteraction.featureGate", true);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.showSearchTerms.enabled", false);
user_pref("browser.search.separatePrivateDefault", true);
user_pref("browser.search.separatePrivateDefault.ui.enabled", true);

/*** [SECTION 0900]: PASSWORDS / FORMS ***/
user_pref("signon.autofillForms", false);
user_pref("signon.formlessCapture.enabled", false);
user_pref("network.auth.subresource-http-auth-allow", 1);
user_pref("browser.formfill.enable", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.maxRichResults", 0);
user_pref("signon.rememberSignons", false);
user_pref("signon.generation.enabled", false);
user_pref("signon.showAutoCompleteFooter", false);
user_pref("signon.autologin.proxy", false);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.sync.enabled", false);

/*** [SECTION 1000]: DISK AVOIDANCE & MEMORY CACHE ***/
user_pref("browser.cache.disk.enable", false);
user_pref("browser.privatebrowsing.forceMediaMemoryCache", true);
user_pref("media.memory_cache_max_size", 65536);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.shell.shortcutFavicons", false);
user_pref("browser.cache.memory.capacity", 262144);
user_pref("browser.sessionhistory.max_total_viewers", 4);
user_pref("browser.sessionstore.max_tabs_undo", 10);

/*** [SECTION 1100]: PERFORMANCE (Network / Process / RAM) ***/
user_pref("browser.sessionstore.interval", 60000);
user_pref("browser.tabs.unloadOnLowMemory", true);
user_pref("browser.low_commit_space_threshold_mb", 13107);
user_pref("browser.low_commit_space_threshold_percent", 20);
user_pref("browser.tabs.min_inactive_duration_before_unload", 300000);
user_pref("dom.ipc.processCount", 8);
user_pref("browser.newtab.preload", false);
user_pref("network.http.max-connections", 1800);
user_pref("network.http.max-persistent-connections-per-server", 10);
user_pref("network.http.pacing.requests.enabled", false);
user_pref("network.ssl_tokens_cache_capacity", 10240);
user_pref("browser.download.start_downloads_in_tmp_dir", true);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.download.manager.addToRecentDocs", false);

/*** [SECTION 1200]: HTTPS / SSL / TLS / CERTS ***/
user_pref("security.ssl.enable_ocsp_stapling", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("security.OCSP.enabled", 0);
user_pref("security.tls.version.min", 3);
user_pref("security.tls.enable_0rtt_data", false);
user_pref("security.tls.version.enable-deprecated", false);
user_pref("security.ssl.require_safe_negotiation", true);
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.remote_settings.crlite_filters.enabled", true);
user_pref("security.pki.crlite_mode", 2);
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_error_page_user_suggestions", true);
user_pref("dom.security.https_only_mode_send_http_background_request", false);

/*** [SECTION 1300]: DOWNLOADS ***/
user_pref("browser.download.open_pdf_attachments_inline", true);
user_pref("pdfjs.enableScripting", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.download.alwaysOpenPanel", false);
user_pref("browser.download.always_ask_before_handling_new_types", true);

/*** [SECTION 1400]: EXTENSIONS ***/
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.postDownloadThirdPartyPrompt", false);

/*** [SECTION 1500]: DOM / MISC ***/
user_pref("dom.disable_window_move_resize", true);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("network.IDN_show_punycode", true);
user_pref("browser.tabs.searchclipboardfor.middleclick", false);
user_pref("browser.contentanalysis.enabled", false);
user_pref("browser.contentanalysis.default_result", 0);
user_pref("security.csp.reporting.enabled", false);
user_pref("privacy.antitracking.isolateContentScriptResources", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.privateWindowSeparation.enabled", false);
user_pref("browser.bookmarks.openInTabClosesMenu", false);
user_pref("browser.menu.showViewImageInfo", true);
user_pref("findbar.highlightAll", true);
user_pref("layout.word_select.eat_space_to_next_word", false);

/*** [SECTION 1600]: REFERERS ***/
user_pref("network.http.referer.XOriginPolicy", 2);
user_pref("network.http.referer.XOriginTrimmingPolicy", 2);
user_pref("network.http.referer.defaultPolicy", 2);
user_pref("network.http.referer.defaultPolicy.pbmode", 2);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault", true);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);

/*** [SECTION 1700]: CONTAINERS / ISOLATION ***/
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);

/*** [SECTION 1800]: PERMISSIONS ***/
user_pref("permissions.default.camera", 2);
user_pref("permissions.default.microphone", 2);
user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);

/*** [SECTION 1900]: UI BEHAVIOR ***/
user_pref("browser.fullscreen.animateUp", 0);
user_pref("full-screen-api.transition-duration.enter", "0 0");
user_pref("full-screen-api.transition-duration.leave", "0 0");
user_pref("apz.overscroll.enabled", false);
user_pref("browser.compactmode.show", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.profiles.enabled", true);
user_pref("layout.css.prefers-color-scheme.content-override", 2);

/*** [SECTION 2000]: PLUGINS / MEDIA / WEBRTC ***/
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("media.getusermedia.screensharing.allowed_domains", "");
user_pref("media.autoplay.default", 5);
user_pref("media.autoplay.blocking_policy", 2);
user_pref("media.volume_scale", "0.0");

/*** [SECTION 2700]: ETP (ENHANCED TRACKING PROTECTION) - STRICT ***/
user_pref("browser.contentblocking.category", "strict");
user_pref("privacy.globalprivacycontrol.enabled", true);

/*** [SECTION 2800]: SHUTDOWN & SANITIZING ***/
user_pref("privacy.sanitize.timeSpan", 0);

/*** [SECTION 4000]: FPP ***/
// ETP Strict auto-enables FPP. No action needed.

/*** [SECTION 4500]: RFP (resistFingerprinting) ***/
// NOT ENABLED - causes too much breakage.
// Enable only if your threat model absolutely requires it.
// See: https://github.com/arkenfox/user.js/wiki/RFP

/*** [SECTION 5000: OPTIONAL OPSEC] ***/
// Higher privacy tier - some breakage. We keep optional out of base config.

/*** [SECTION 6000]: DON'T TOUCH - core browser functionality ***/
user_pref("extensions.blocklist.enabled", true);
user_pref("network.http.referer.spoofSource", false);
user_pref("security.dialog_enable_delay", 1000);
user_pref("privacy.firstparty.isolate", false);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat-reporter.enabled", false);
user_pref("extensions.quarantinedDomains.enabled", true);
/*** [SECTION 8500]: FULL METRICS SHUTDOWN ***/
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");
user_pref("datareporting.usage.uploadEnabled", false);
user_pref("toolkit.telemetry.dap_enabled", false);
user_pref("dom.private-attribution.submission.enabled", false);

/*** [SECTION 9000]: EXTRAS / BLOAT KILLSWITCHES ***/
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.preferences.moreFromMozilla", false);
user_pref("browser.uitour.enabled", false);
user_pref("browser.uitour.url", "");
user_pref("browser.firefox-view.feature-tour", false);

/* Firefox Sync / Accounts - completely disable */
user_pref("identity.fxaccounts.enabled", false);
user_pref("services.sync.enabled", false);
user_pref("services.sync.engine.tabs", false);
user_pref("services.sync.engine.history", false);
user_pref("services.sync.engine.passwords", false);
user_pref("services.sync.engine.bookmarks", false);
user_pref("services.sync.engine.prefs", false);
user_pref("services.sync.engine.addons", false);
user_pref("services.sync.engine.extensions", false);
user_pref("services.sync.engine.clients", false);
user_pref("browser.uidb.enabled", false);

/* Firefox Translate - completely disable */
user_pref("browser.translations.enable", false);
user_pref("browser.translations.autoTranslate", false);
user_pref("browser.translations.ui.enabled", false);

/* Pocket integration - remove sponsored content bloat */
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.oAuthConsumerKey", "");
user_pref("extensions.pocket.api", "");
user_pref("extensions.pocket.site", "");
user_pref("extensions.pocket.showHome", false);

/* AI / ML features - block all */
user_pref("browser.ai.control.default", "blocked");
user_pref("browser.ml.enable", false);
user_pref("browser.ml.chat.enabled", false);
user_pref("browser.ml.chat.menu", false);
user_pref("browser.ml.linkPreview.enabled", false);
user_pref("browser.tabs.groups.smart.enabled", false);

/* Disable experiments */
user_pref("browser.experiments.active", false);

/* Zen UI mode: false = compact (autohide), true = full (always visible) */
user_pref("zen.mode.full", false);

/* Dark mode everywhere (UI + websites) */
user_pref("layout.css.prefers-color-scheme.content-override", 0);
user_pref("browser.theme.dark-private-windows", false);
user_pref("ui.systemUsesDarkTheme", 1);

/*** [FINAL CHECK] ***/
user_pref("_user.js.parrot", "SUCCESS: he's resting, pining for the fjords!");

/********************************************************************\
 *  POST-INSTALL CHECKLIST
 *
 *  [ ] ETP Strict dialog confirmed (about:preferences#privacy)
 *  [ ] HTTPS-Only Mode enabled (url bar shows lock icon)
 *  [ ] DoH working (about:networking#dns shows "TRR")
 *  [ ] Native vertical tabs visible (View -> Sidebar -> Vertical Tabs)
 *  [ ] Sidebar debloated (no AI Chat, no Synced Tabs icons)
 *  [ ] Test: https://browserleaks.com/ and https://coveryourtracks.eff.org/
 *
 *  REPORT BREAKED SITES:
 *    Right-click Site Information > "Report Broken Site" in ETP dropdown
 *    Or go to user-overrides.js and add:
 *      user_pref("...specific.pref", ...value);
 *
 *  Want Tor-level anonymity?
 *    - DO NOT enable RFP
 *    - Download / use Tor Browser instead
 *
 \\********************************************************************/
